version: '3'
services:
  sonar:
    container_name: sonarqube
    image: sonarqube:8.4.1-community
    ports:
      - "7000:9000"


  mongo-db:
    image: mongo
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/ricardo/Documents/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongo-db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge